apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sap-btp-operator-migration
rules:
  - apiGroups:
    - "apiextensions.k8s.io"
    resources:
    - customresourcedefinitions
    verbs:
    - get
    - list
    - delete
  - apiGroups:
    - ""
    resources:
    - "*"
    verbs:
    - get
    - list
    - watch
    - patch
    - update
    - delete
  - apiGroups:
    - "servicecatalog.kyma-project.io"
    - "admissionregistration.k8s.io"
    - "services.cloud.sap.com"
    - "rbac.authorization.k8s.io"
    - "monitoring.coreos.com"
    - "security.istio.io"
    - "ui.kyma-project.io"
    - "testing.kyma-project.io"
    - "servicecatalog.k8s.io"
    - "apps"
    - "apiextensions.k8s.io"
    - "networking.istio.io"
    - "policy"
    - "security.istio.io"
    - "addons.kyma-project.io"
    - "serverless.kyma-project.io"
    verbs:
    - "*"
    resources:
    - "*"
