apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sap-btp-operator-migration
rules:
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
    - customresourcedefinitions
  verbs:
    - get
    - list
- apiGroups:
    - "apps"
  resources:
    - customresourcedefinitions
  verbs:
    - get
    - list
    - delete
- apiGroups:
    - "rbac.authorization.k8s.io apps"
  resources:
    - customresourcedefinitions
  verbs:
    - get
    - list
    - delete
- apiGroups:
  - "admissionregistration.k8s.io"
  resources:
    - "*"
  verbs:
    - get
    - list
    - delete
- apiGroups:
  - ""
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
  - patch
  - update
  - delete
- apiGroups:
  - ""
  resources:
  # needs to get sap-btp-operator ConfigMap 
  - configmaps
  - customresourcedefinitions
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - services.cloud.sap.com
  - servicecatalog.k8s.io
  resources:
  - servicebindings
  - serviceinstances
  - servicebrokers
  - clusterservicebrokers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - deletecollection
- apiGroups:
  - servicecatalog.kyma-project.io
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - deletecollection
  resources:
  - servicebindingusages