apiVersion: batch/v1
kind: Job
metadata:
  name: sap-btp-operator-migration
  namespace: {{.Release.Namespace}}
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: sap-btp-operator-migration
      restartPolicy: Never
      containers:
        - name: migration
          command:
            - sap-btp-service-operator-migration
            - run
          image: {{.Values.image.repository}}:{{.Values.image.tag}}
          imagePullPolicy: Always
